project:
  type: website

website:
  title: "Eric M. Baumel, MD"
  site-url: https://ericbaumel.com
  favicon: favicon.ico
  open-graph:
    title: "Eric M. Baumel, MD"
    description: "Radiologist, app developer, and medical 3D printing innovator. Blog covering coding, data science, and digital health."
    image: Eric_Baumel.png
  twitter-card:
    title: "Eric M. Baumel, MD"
    description: "Radiologist, app developer, and medical 3D printing innovator. Blog covering coding, data science, and digital health."
    image: Eric_Baumel.png
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/in/ericbaumel/
      - icon: github
        href: https://github.com/ebaumel
      - icon: bluesky
        href: https://bsky.app/profile/ebaumel.bsky.social
format:
  html:
    theme: cosmo
    css: styles.css



