project:
  type: website

website:
  title: "Eric M. Baumel, MD"
  site-url: https://ericbaumel.com
  favicon: favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/in/ericbaumel/
      - icon: github
        href: https://github.com/ebaumel
      - icon: fa-brands fa-bluesky
        href: https://bsky.app/profile/ebaumel.bsky.social
format:
  html:
    theme: cosmo
    css: styles.css



