project:
  type: website

website:
  title: "Eric M. Baumel, MD"
  site-url: https://ericbaumel.com
  favicon: favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ebaumel
format:
  html:
    theme: cosmo
    css: styles.css



